version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    volumes:
      - ./:/micro-blog-app
      - /micro-blog-app/node_modules
    environment:
      - PORT=4000
      - APP_NAME=micro-blog-app

    deploy:
      replicas: 1

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 090912
      POSTGRES_DB: blog_app
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    environment:
      - TZ=UTC

volumes:
  postgres_data:
  redis_data:

