version: "3"
services:
  node-app:
    build:
      context: .
      args: 
       NODE_ENV: development
    volumes:
      - ./:/micro-blog-app
      - /micro-blog-app/node_modules
    environment:
      - NODE_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=090912
      - POSTGRES_DB=blog_app
      - POSTGRES_PORT=5432

    command: npm run apollo
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=090912

 